#lang racket

#|
PROBLEM 29: DISTINCT POWERS
consider all integer combinations of a^b for 2 <= a <= 5
and a <= b <= 5:

2^2 = 4,
2^3 = 8,
2^4 = 16,
3^2 = 9,
3^3 = 27,
3^4 = 81,
3^5 = 243,
2^5 = 32,
4^2 = 16, 
4^3 = 64, 
4^4 = 256,
4^5 = 1024
5^2 = 25,
5^3 = 125,
5^4 = 625,
5^5 = 3125

if they are placedi n numerical order with any repeas removed
we get the following seq of 15 distinct terms:

4,8,9,16,25,27,32,64,81,125,243,256,625,1024,3125
how many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and
2 <= b <= 100

answer:
ok let me understand the question

we want to find how many distinct terms in seq generated
a^b for 2 <= a <= 100 and 2 <= b <= 100

so in the example its just increasing power and increasing base with that limit

approach, need a function to find value for each fixed base
- outer loop: fix a (base)
- for each a, increment power
- then move on to next a
- count distinct results (unique set thing)


find the numbers
so starts with base 2 -> check power from 2 up to 100, then move
ot base 3 -> repeat
is this toolong? maybe i souldnt worry about efficiency yet
hmm doi fix the base or the power, or maybe i'm tackling this in the wrong way?

|#

; given a base number, gnerates its power sequence from base^2 to base^100
; number -> list-of-number
(define (generate-power-seq base)
  (map (λ (n) (expt base n)) (range 2 101))
  )
;(generate-power-seq 2) ;(2,8,16,32,...)

; given two lists, returns it unique union set
; list-of-x list-of-x -> list-of-y
(define (union xs ys)
  ; let ys is the accumulator/list thath oldsresult
  (cond [(null? xs) ys]
        [(null? ys) xs]
        [(member (car xs) ys) (union (cdr xs) ys)] ;skip
        [else (cons (car xs) (union (cdr xs) ys))]
        )
  )
(union '() '()) ; '()
(union '(1 2 3) '()) ; '(1 2 3)
(union '() '(1 5)) ; '(1 2)
(union '(1) '(2)) ; '(1 2)
(union '(1 2 3 4 5) '(1 5 7 8 9)) ;'(2 3 4 1 5 7 8 9)


list->set
; finds how many distinct terms in seq generated by a^b for 2 <= a <= 100 and 2 <= b <= 100
; void -> number
(define (distinct-powers)

  #|
  (define (helper curr-b result)
    (cond [(> curr-b 100) result]
          [else (let* ((curr-power-seq (generate-power-seq curr-b))
                       (next-power-seq (generate-power-seq (+ curr-b 1)))
                       (unique-count (length (union curr-power-seq next-power-seq))))
                  (helper (+ curr-b 1) (+ unique-count result))
                  ) ]
          )
    )
  (helper 2 0)
  |#

  (let ((xxs (map generate-power-seq (range 2 101)) ))
    (length (foldr (λ (xs acc) (union xs acc) ) '() xxs))
    )
  )
(distinct-powers)