#lang racket



#|
PROBLEM 2: EVEN FIBONACCI NUMBERS

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with  and , the first  terms will be: 1,2,3,5,8,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
|#

#|
; VERSION 1
; main proc to generate fibonacci list up to n
; number -> list-of-number
(define (fib-up-to value)
  (define (helper a b result)
    (cond [(> a value) (reverse result)]
          [else (helper b (+ a b) (cons a result) )]
          )
    )
  ; initialize with a=1 and b=2
  (helper 1 2 '())
  )
(fib-up-to 4000000) ; (1 2 3 5 8 13)
|#



; VERSION 2 ;; calculate the sum
(define (fib-up-to value)
  ; number number number -> number
  (define (helper a b result)
    (cond [(> a value) result]
          [(even? a) (helper b (+ a b) (+ a result))]
          [else (helper b (+ a b) result)] ;skip it
          )
    )
  ; initialize with a=1 and b=2
  (helper 1 2 0)
  )
(fib-up-to 4000000)



#|
(define (even-fib-up-to n)
  (foldr + 0 (filter even? (fib-up-to n)))
  )
(even-fib-up-to 4000000)
|#