#lang racket

#|

Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers. So the
7th triangle number would be 1+2+3+4+5+6+7 = 28. the first 10 terms would be:

1,3,6,10,15,21,28,36,45,55,...

Let us list the factors of the first seven triangle numbers:


1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28


We can see that 28  is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

answer:

ok so the question wants me to find the first triangle number to have < 500 divisors
let me simplify the problem

first triangle number to have <5 divisors -> 28 since 21 has only 4 factors

lets keep this simple, so the general plan
1. generate the list of trianglular number terms
2. for each of the term, gather factors factors and check if its > 500
3. if the factors are <= 500, keep searching


|#

; triangle-number:: given a number, returns a triangle value based on that term
; number -> number
; term 1 -> 1, term 2 -> 1+2 = 3, term 3 -> 1+2+3 = 6
(define (triangle-number term)
  (foldr + 0 (range 1 (+ 1 term)))
  )
(triangle-number 1)
(triangle-number 2)
(triangle-number 3)
(triangle-number 4)
(triangle-number 5)
(triangle-number 6)

; number -> list-of-number
; given a number, returns a list of factors of that number.
; i dont rememeber hw to find factors maybe smth like this
(define (factors-of n)
  ; new n is the remainder
  ; cant be divided, skip and add + 1
  (define (loop curr-n curr-fact result)
    (cond [(> curr-fact (sqrt n)) result] 
          [(zero? (remainder curr-n curr-fact)) (if (= (quotient curr-n curr-fact) curr-fact)
                                                    (loop curr-n (+ 1 curr-fact) (cons curr-fact result) )
                                                    (loop curr-n (+ 1 curr-fact) (cons curr-fact (cons (quotient curr-n curr-fact) result)))
                                                    )] ;divides perfectly, add to result
          [else (loop curr-n  (+ 1 curr-fact) result)] ;increment curr-fact
          )
    )
  (loop n 1 '())
  )
(factors-of 21) ; 1,3,7,21
(factors-of 28) ; 1,2,4,7,14,28

; given a number, finds the first value triangle number with over n total divisors
; number -> number
(define (triangle-number-with-over-n-divisors n)
  (define (loop curr-tri-val curr-term)
    (let ((curr-factors (factors-of curr-tri-val)))
      (cond [(> (length curr-factors) n) curr-tri-val ] ;found
            [else (loop (triangle-number (+ 1 curr-term)) (+ 1 curr-term) )] ;keep searching
            )
      )
    )
  (loop (triangle-number 1) 1)
  )
(triangle-number-with-over-n-divisors 1) ; 3
(triangle-number-with-over-n-divisors 2) ; 6
(triangle-number-with-over-n-divisors 3) ; 6
(triangle-number-with-over-n-divisors 4) ; 28
(triangle-number-with-over-n-divisors 5) ; 28
(triangle-number-with-over-n-divisors 10) ; 120
(triangle-number-with-over-n-divisors 500) ;76576500


